/*
Copyright 2018 The Openshift Evangelists

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// This file was automatically generated by informer-gen

package v1

import (
	dev_kubernetes_pavanvelidandla_com_v1 "crds/pkg/apis/dev.kubernetes.pavanvelidandla.com/v1"
	versioned "crds/pkg/client/clientset/versioned"
	internalinterfaces "crds/pkg/client/informers/externalversions/internalinterfaces"
	v1 "crds/pkg/client/listers/dev/v1"
	meta_v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
	time "time"
)

// ConfigFromGitInformer provides access to a shared informer and lister for
// ConfigFromGits.
type ConfigFromGitInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1.ConfigFromGitLister
}

type configFromGitInformer struct {
	factory internalinterfaces.SharedInformerFactory
}

// NewConfigFromGitInformer constructs a new informer for ConfigFromGit type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewConfigFromGitInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options meta_v1.ListOptions) (runtime.Object, error) {
				return client.DevV1().ConfigFromGits(namespace).List(options)
			},
			WatchFunc: func(options meta_v1.ListOptions) (watch.Interface, error) {
				return client.DevV1().ConfigFromGits(namespace).Watch(options)
			},
		},
		&dev_kubernetes_pavanvelidandla_com_v1.ConfigFromGit{},
		resyncPeriod,
		indexers,
	)
}

func defaultConfigFromGitInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewConfigFromGitInformer(client, meta_v1.NamespaceAll, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc})
}

func (f *configFromGitInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&dev_kubernetes_pavanvelidandla_com_v1.ConfigFromGit{}, defaultConfigFromGitInformer)
}

func (f *configFromGitInformer) Lister() v1.ConfigFromGitLister {
	return v1.NewConfigFromGitLister(f.Informer().GetIndexer())
}
